
--------------------------------------------------------
--  DDL for Table PERFIL_ADJUDICACION
--------------------------------------------------------

  CREATE TABLE "PERFIL_ADJUDICACION" 
   (	"ID_ADJU" NUMBER, 
	"EXPEDIENTE" VARCHAR2(200 BYTE), 
	"NIF_ADJU" VARCHAR2(200 BYTE), 
	"ADJUD" VARCHAR2(200 BYTE), 
	"FECHA_ADJ" DATE, 
	"FECHA_FORM" DATE, 
	"IMPORTE" NUMBER, 
	"EJECUCION" VARCHAR2(200 BYTE), 
	"CANON" VARCHAR2(20 BYTE) DEFAULT 'No', 
	"AUTONOMO" VARCHAR2(20 BYTE) DEFAULT 'N', 
	"GANADOR" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"IMPORTE_CONIVA" NUMBER, 
	"ID_CONTRATO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_ANUNCIO
--------------------------------------------------------

  CREATE TABLE "PERFIL_ANUNCIO" 
   (	"ID_ANUNCIO" NUMBER, 
	"TITULO" VARCHAR2(4000 BYTE), 
	"TEXTO" CLOB, 
	"ADJUNTO" BLOB, 
	"ID_CONTRATO" NUMBER, 
	"ID_TIPOANUNCIO" NUMBER, 
	"GCZ_FECHAALTA" DATE, 
	"GCZ_FECHAMOD" DATE DEFAULT NULL, 
	"GCZ_FECHACAD" DATE, 
	"NOMBRADJUNTO" VARCHAR2(255 BYTE), 
	"GCZ_PUBLICADO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"GCZ_FECHAPUB" DATE DEFAULT NULL, 
	"GCZ_USUARIOALTA" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"GCZ_USUARIOMOD" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"GCZ_USUARIOPUB" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"VISUALIZARPRIMERA" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"FUENTE_PUBLICACION" VARCHAR2(2000 BYTE), 
	"ID_LENGUAJE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("TEXTO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ADJUNTO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PERFIL_CONTRATO
--------------------------------------------------------

  CREATE TABLE "PERFIL_CONTRATO" 
   (	"ID_CONTRATO" NUMBER, 
	"NOMBRE" VARCHAR2(2000 BYTE), 
	"ID_TIPOCONTRATO" NUMBER, 
	"GCZ_FECHAALTA" DATE, 
	"GCZ_FECHAMOD" DATE DEFAULT NULL, 
	"GCZ_FECHACAD" DATE, 
	"ID_PORTAL" NUMBER, 
	"ESTADO" NUMBER DEFAULT -1, 
	"FECHA_PRESENTACION" DATE, 
	"GCZ_PUBLICADO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"GCZ_FECHAPUB" DATE DEFAULT NULL, 
	"GCZ_USUARIOALTA" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"GCZ_USUARIOMOD" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"GCZ_USUARIOPUB" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"EXPEDIENTE" VARCHAR2(50 BYTE), 
	"CONT_MENOR" VARCHAR2(1 BYTE), 
	"ID_PROCEDIMIENTO" NUMBER, 
	"SERVICIO_GESTOR" NUMBER, 
	"DURACION" NUMBER, 
	"CPV" NUMBER, 
	"OBJETO" VARCHAR2(2000 BYTE), 
	"FECHA_ADJ" DATE, 
	"FECH_FORM" DATE, 
	"LICITADORES" NUMBER, 
	"URGENTE" VARCHAR2(20 BYTE) DEFAULT 'N', 
	"IMPORTE_CONIVA" NUMBER, 
	"IMPORTE_SINIVA" NUMBER, 
	"VALOR_ESTIMADO" NUMBER, 
	"LOTES" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"DERIVADOACUERDOMARCO" VARCHAR2(1 BYTE), 
	"DERIVADOSISTEMADINAMICO" VARCHAR2(1 BYTE), 
	"CONSUBASTAELECTRONICA" VARCHAR2(1 BYTE), 
	"COMPLEMENTARIO" VARCHAR2(1 BYTE), 
	"REGULACIONARMONIZADA" VARCHAR2(1 BYTE), 
	"PLAZOCONSESION" NUMBER, 
	"CLAUSULAPRORROGA" VARCHAR2(1 BYTE), 
	"PERIODOPRORROGA" NUMBER, 
	"ORGANO_CONTRATACION" NUMBER, 
	"DURACION_REAL" NUMBER, 
	"IVA" NUMBER, 
	"GCZ_FECHACONTRATO" DATE, 
	"CANON" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ID_PADRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "PERFIL_CONTRATO"."URGENTE" IS 'S: Urgente
N: Ordinaria
E: ¿Excepcional? Tribunal de cuentas';
 
   COMMENT ON COLUMN "PERFIL_CONTRATO"."DERIVADOACUERDOMARCO" IS 'Interoperabilidad Tribunal de cuentas';
 
   COMMENT ON COLUMN "PERFIL_CONTRATO"."DERIVADOSISTEMADINAMICO" IS 'Interoperabilidad Tribunal de cuentas';
 
   COMMENT ON COLUMN "PERFIL_CONTRATO"."CONSUBASTAELECTRONICA" IS 'Interoperabilidad Tribunal de cuentas';
 
   COMMENT ON COLUMN "PERFIL_CONTRATO"."COMPLEMENTARIO" IS 'Interoperabilidad Tribunal de cuentas';
 
   COMMENT ON COLUMN "PERFIL_CONTRATO"."REGULACIONARMONIZADA" IS 'Interoperabilidad Tribunal de cuentas';
 
   COMMENT ON COLUMN "PERFIL_CONTRATO"."PLAZOCONSESION" IS 'Interoperabilidad Tribunal de cuentas';
 
   COMMENT ON COLUMN "PERFIL_CONTRATO"."CLAUSULAPRORROGA" IS 'Interoperabilidad Tribunal de cuentas';
 
   COMMENT ON COLUMN "PERFIL_CONTRATO"."PERIODOPRORROGA" IS 'Interoperabilidad Tribunal de cuentas';
 
   COMMENT ON COLUMN "PERFIL_CONTRATO"."ID_PADRE" IS 'Relacionar contratos derivados';
--------------------------------------------------------
--  DDL for Table PERFIL_CONTRATO_TIENE_CPV
--------------------------------------------------------

  CREATE TABLE "PERFIL_CONTRATO_TIENE_CPV" 
   (	"ID_CONTRATO" NUMBER, 
	"CPV" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_CPV
--------------------------------------------------------

  CREATE TABLE "PERFIL_CPV" 
   (	"ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(172 BYTE), 
	"ESTADO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_CRITERIOS
--------------------------------------------------------

  CREATE TABLE "PERFIL_CRITERIOS" 
   (	"ID_CRITERIO" NUMBER, 
	"ID_CONTRATO" VARCHAR2(20 BYTE), 
	"TITULO" VARCHAR2(2000 BYTE), 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"TIPO" VARCHAR2(200 BYTE), 
	"PESO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_EMPRESA
--------------------------------------------------------

  CREATE TABLE "PERFIL_EMPRESA" 
   (	"ID_EMPRESA" NUMBER, 
	"LIBREBORME" VARCHAR2(2000 BYTE), 
	"UTE" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"NOMBRE" VARCHAR2(2000 BYTE), 
	"NIF" VARCHAR2(200 BYTE), 
	"AUTONOMO" VARCHAR2(1 BYTE), 
	"NACIONALIDAD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_ESTADOS
--------------------------------------------------------

  CREATE TABLE "PERFIL_ESTADOS" 
   (	"ID_ESTADO" NUMBER(14,0), 
	"NOMBRE" VARCHAR2(100 BYTE) DEFAULT ''
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_IDIOMA
--------------------------------------------------------

  CREATE TABLE "PERFIL_IDIOMA" 
   (	"ID" NUMBER, 
	"CODIGO" NVARCHAR2(20), 
	"IDIOMA" NVARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_LOTE
--------------------------------------------------------

  CREATE TABLE "PERFIL_LOTE" 
   (	"ID_LOTE" NUMBER, 
	"ID_CONTRATO" NUMBER, 
	"DESCRIPCION" VARCHAR2(2000 BYTE), 
	"IMPORTE_LICITACION_LOTE_SINIVA" NUMBER, 
	"IMPORTE_LICITACION_LOTE_CONIVA" NUMBER, 
	"ESTADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_LOTE_TIENE_OFERTA
--------------------------------------------------------

  CREATE TABLE "PERFIL_LOTE_TIENE_OFERTA" 
   (	"ID_LOTE" NUMBER, 
	"ID_OFERTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_OFERTA
--------------------------------------------------------

  CREATE TABLE "PERFIL_OFERTA" 
   (	"ID_OFER" NUMBER, 
	"EXPEDIENTE" VARCHAR2(200 BYTE), 
	"NIF" VARCHAR2(200 BYTE), 
	"OFER" VARCHAR2(200 BYTE), 
	"FECHA_ADJ" DATE, 
	"FECHA_FORM" DATE, 
	"IMPORTE_SINIVA" NUMBER, 
	"EJECUCION" VARCHAR2(200 BYTE), 
	"CANON" VARCHAR2(20 BYTE) DEFAULT 'No', 
	"AUTONOMO" VARCHAR2(20 BYTE) DEFAULT 'N', 
	"GANADOR" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"IMPORTE_CONIVA" NUMBER, 
	"ID_CONTRATO" NUMBER, 
	"UTE" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ID_EMPRESA" NUMBER, 
	"AHORRO_VISIBLE" CHAR(1 BYTE) DEFAULT 'S', 
	"IVA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_PORTAL
--------------------------------------------------------

  CREATE TABLE "PERFIL_PORTAL" 
   (	"ID_PORTAL" NUMBER, 
	"NOMBRE" VARCHAR2(500 BYTE), 
	"USUARIO" VARCHAR2(30 BYTE), 
	"CLAVE" VARCHAR2(100 BYTE), 
	"CARPETA" VARCHAR2(100 BYTE), 
	"GCZ_PUBLICADO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"GCZ_FECHAALTA" DATE, 
	"GCZ_FECHAMOD" DATE DEFAULT NULL, 
	"GCZ_FECHAPUB" DATE DEFAULT NULL, 
	"GCZ_USUARIOALTA" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"GCZ_USUARIOMOD" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"GCZ_USUARIOPUB" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"SERVICIO_GESTOR_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_PROCEDIMIENTO
--------------------------------------------------------

  CREATE TABLE "PERFIL_PROCEDIMIENTO" 
   (	"NOMBRE" VARCHAR2(2000 BYTE), 
	"ID_PROC" NUMBER, 
	"TYPE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_SELLO
--------------------------------------------------------

  CREATE TABLE "PERFIL_SELLO" 
   (	"ID_ANUNCIO" NUMBER, 
	"PERMALINK" VARCHAR2(255 BYTE), 
	"FIRMA" CLOB, 
	"CONTENIDO" CLOB, 
	"IDPUBLICACIONFEHACIENTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("FIRMA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("CONTENIDO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PERFIL_TIPOANUNCIO
--------------------------------------------------------

  CREATE TABLE "PERFIL_TIPOANUNCIO" 
   (	"ID_TIPOANUNCIO" NUMBER, 
	"NOMBRE" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_TIPOCONTRATO
--------------------------------------------------------

  CREATE TABLE "PERFIL_TIPOCONTRATO" 
   (	"ID_TIPOCONTRATO" NUMBER, 
	"NOMBRE" VARCHAR2(500 BYTE), 
	"TYPE" VARCHAR2(100 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_TIPOCRITERIO
--------------------------------------------------------

  CREATE TABLE "PERFIL_TIPOCRITERIO" 
   (	"ID_TIPO" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_UTE
--------------------------------------------------------

  CREATE TABLE "PERFIL_UTE" 
   (	"ID_UTE" NUMBER, 
	"ID_EMPRESA" NUMBER, 
	"POR_PAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
