 CREATE TABLE "V00010_JERARQUIA_ORGANIGRAMA" 
   (	"ID" NUMBER(5,0), 
	"TITLE" VARCHAR2(128), 
	"NOMBRE_ESTR" VARCHAR2(128), 
	"ID_CEN" NUMBER, 
	"NOMBRE_CEN" VARCHAR2(125), 
	"EMAIL" VARCHAR2(50), 
	"PHONE" VARCHAR2(1000), 
	"FAX" VARCHAR2(18), 
	"POSTAL_CODE" VARCHAR2(5), 
	"ADDRESS" VARCHAR2(361), 
	"PORTAL" NUMBER(10,0), 
	"CODIGO_AREA" NUMBER, 
	"NOMBRE_AREA" VARCHAR2(4000), 
	"X" NUMBER, 
	"Y" NUMBER, 
	"NIVEL_ADMINISTRACION" NUMBER, 
	"TIPO_ENTIDAD_PUBLICA" CHAR(2), 
	"NIVEL_JERARQUICO" NUMBER, 
	"UNIDAD_SUPERIOR" NUMBER(5,0), 
	"FECHA_ALTA" DATE, 
	"FECHA_BAJA" DATE, 
	"COMPETENCIAS" VARCHAR2(4000 CHAR), 
	"UNIDAD_RAIZ" NUMBER, 
	"ESTADO" CHAR(1), 
	"EMPLEADO_RESPONSABLE" VARCHAR2(500), 
	"CODIGO_DIR3" VARCHAR2(50)
   ) ;

SET DEFINE OFF;
Insert into V00010_JERARQUIA_ORGANIGRAMA (ID,TITLE,NOMBRE_ESTR,ID_CEN,NOMBRE_CEN,EMAIL,PHONE,FAX,POSTAL_CODE,ADDRESS,PORTAL,CODIGO_AREA,NOMBRE_AREA,X,Y,NIVEL_ADMINISTRACION,TIPO_ENTIDAD_PUBLICA,NIVEL_JERARQUICO,UNIDAD_SUPERIOR,FECHA_ALTA,FECHA_BAJA,COMPETENCIAS,UNIDAD_RAIZ,ESTADO,EMPLEADO_RESPONSABLE,CODIGO_DIR3) values ('1','Ayntamiento','Oficina Municipal de Apoyo al Ciudadano','2498','Ayuntamiento','ayuntamiento@zaragoza.es','123123','123123','50071','Plaza Pilar','12','3','Alcaldia','676241','4613975','1','S ','1',null,null,null,'texto de competencias','1','V','nombre persona',null);
Insert into V00010_JERARQUIA_ORGANIGRAMA (ID,TITLE,NOMBRE_ESTR,ID_CEN,NOMBRE_CEN,EMAIL,PHONE,FAX,POSTAL_CODE,ADDRESS,PORTAL,CODIGO_AREA,NOMBRE_AREA,X,Y,NIVEL_ADMINISTRACION,TIPO_ENTIDAD_PUBLICA,NIVEL_JERARQUICO,UNIDAD_SUPERIOR,FECHA_ALTA,FECHA_BAJA,COMPETENCIAS,UNIDAD_RAIZ,ESTADO,EMPLEADO_RESPONSABLE,CODIGO_DIR3) values ('23960','prueba','prueba','533','Prueba',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
